//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleoTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\World of Warcraft\\_classic_\\WTF\\Account\\OFFSPREY\\SavedVari" +
            "ables\\Cleo.lua")]
        public string CleoConfigLoc {
            get {
                return ((string)(this["CleoConfigLoc"]));
            }
            set {
                this["CleoConfigLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cleo_DB>global>cache>player>")]
        public string ToonCache {
            get {
                return ((string)(this["ToonCache"]));
            }
            set {
                this["ToonCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cleo_Lists>factionrealm>Alliance - Atiesh>configurations>634442A9-6586-D664-5DB7-" +
            "DEA8147C6E33>alts")]
        public string AltMapping {
            get {
                return ((string)(this["AltMapping"]));
            }
            set {
                this["AltMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cleo_Lists>factionrealm>Alliance - Atiesh>lists>63446602-2A74-DAD4-6934-BE542E7DB" +
            "A8E>players")]
        public string ActivePlayerList {
            get {
                return ((string)(this["ActivePlayerList"]));
            }
            set {
                this["ActivePlayerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cleo_Lists>factionrealm>Alliance - Atiesh>configurations>")]
        public string LootConfigs {
            get {
                return ((string)(this["LootConfigs"]));
            }
            set {
                this["LootConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cleo_Lists>factionrealm>Alliance - Atiesh>lists>")]
        public string LootLists {
            get {
                return ((string)(this["LootLists"]));
            }
            set {
                this["LootLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\offsp\\Documents\\")]
        public string OutputLoc {
            get {
                return ((string)(this["OutputLoc"]));
            }
            set {
                this["OutputLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Booze:Erboozel}{Kerri/Ann:Kerridwen}{Z-Zealót/Zoidbérg:Zealót}{Jackburton:Jackbu" +
            "rtón}{Path:Octane}{Jekka/Febra:Febra}{Missed:Missedshift}{Saekosan/Kagari:Kagari" +
            "}{Tarazed/Illuminarin:Illuminarin}{Viki:Vikai}{Zhitnik:Valjean}")]
        public string DiscordUserMapping {
            get {
                return ((string)(this["DiscordUserMapping"]));
            }
            set {
                this["DiscordUserMapping"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\offsp\\source\\repos\\O" +
            "ffsprey\\CleoTool\\CleoTool\\CleoToolDB.mdf;Integrated Security=True;Connect Timeou" +
            "t=30")]
        public string CleoToolDBConnectionString {
            get {
                return ((string)(this["CleoToolDBConnectionString"]));
            }
        }
    }
}
