//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleoTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Booze/Felie:Erboozel}{Kerri/Ann:Kerridwen}{Z-Zealót/Zoidbérg:Zealót}{Jackburton:" +
            "Jackburtón}{Path:Octane}{Jekka/Febra:Febra}{Prayermayor/Rarebear:Snarebear}")]
        public string DiscordUserMapping {
            get {
                return ((string)(this["DiscordUserMapping"]));
            }
            set {
                this["DiscordUserMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
<!--StartFragment--><google-sheets-html-origin><style type=""text/css""><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-cell;}--></style><table xmlns=""http://www.w3.org/1999/xhtml"" cellspacing=""0"" cellpadding=""0"" dir=""ltr"" border=""1"" style=""table-layout:fixed;font-size:10pt;font-family:Arial;width:0px;border-collapse:collapse;border:none""><colgroup><col width=""100""/></colgroup><tbody><tr style=""height:21px;""><td style=""overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;"" data-sheets-value=""{&quot;1&quot;:2,&quot;2&quot;:&quot;Test1&quot;}"">Test1</td></tr><tr style=""height:21px;""><td style=""overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;color:#ff0000;"" data-sheets-value=""{&quot;1&quot;:2,&quot;2&quot;:&quot;Test2&quot;}"">Test2</td></tr><tr style=""height:21px;""><td style=""overflow:hidden;padding:2px 3px 2px 3px;vertical-align:bottom;font-weight:bold;"" data-sheets-value=""{&quot;1&quot;:2,&quot;2&quot;:&quot;Test3&quot;}"">Test3</td></tr></tbody></table><!--EndFragment-->
</body>
</html>")]
        public string GoogleSheetsPaste {
            get {
                return ((string)(this["GoogleSheetsPaste"]));
            }
            set {
                this["GoogleSheetsPaste"] = value;
            }
        }
    }
}
